name: workflow ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        cache-dependency: 'sub-project/pom.xml'

    - name: clean
      run: mvn clean
    - name: compile
      run: mvn validate compile
    - name: unit tests
      run: mvn test -Dtest=!resource/*
    - name: integration tests
      run: mvn test -Dtest=resource/*
    - name: package
      run: mvn  package verify -DskipTests
